- name: Build and Push Docker Image
  hosts: localhost
  become: true
  become_user: terno
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    docker_host: "unix:///var/run/docker.sock"
    
  tasks:
    - name: Remove an image
      community.docker.docker_image_remove:
        name: terno9144/jenkins_images:latest
        force: true

    - name: Log into DockerHub
      docker_login:
        api_version: "1.45"
        username: terno9144
        password: "{{ lookup('env', 'docker_pass') }}"

    - name: Build Nginx image
      community.docker.docker_image_build:
        name: terno9144/jenkins_images
        tag: latest
        path: "{{ playbook_dir }}"
        dockerfile: Dockerfile

    - name: Push Docker image
      community.docker.docker_image:
        api_version: "1.45"
        name: terno9144/jenkins_images
        tag: latest
        docker_host: "unix:///var/run/docker.sock"
        push: true
        source: local

    # - name: Start a container with a command
    #   community.docker.docker_container:
    #     name: my-nginx
    #     image: terno9144/jenkins_images:latest
    #     ports:
    #       - "8084:80"

    # - name: Check if index.html is accessible
    #   command: curl -o /dev/null -s -w "%{http_code}" http://localhost:8084
    #   register: curl_result

    # - name: 
    #   debug: 
    #     msg: "{{ curl_result }}"
    #   when: curl_result

    # - name: Validate HTTP response
    #   fail:
    #     msg: "The HTTP response is not 200! Something went wrong."
    #   when: curl_result.stdout != "200"
