- name: Build and Push Docker Image
  hosts: localhost
  become: true
  vars:
    unique_tag: "{{ ansible_date_time.iso8601_basic_short }}"
    
  tasks:
    - name: Remove an image
      community.docker.docker_image_remove:
        name: terno9144/jenkins_images:latest
        force: true

    - name: Log into DockerHub
      docker_login:
        api_version: "1.45"
        username: terno9144
        password: "{{ lookup('env', 'docker_pass') }}"

    - name: Build Nginx image
      community.docker.docker_image_build:
        name: terno9144/jenkins_images
        tag: "{{ unique_tag }}"
        path: "{{ playbook_dir }}"
        dockerfile: Dockerfile

    - name: Push Docker image
      community.docker.docker_image:
        api_version: "1.45"
        name: terno9144/jenkins_images
        tag: "{{ unique_tag }}"
        docker_host: "unix:///var/run/docker.sock"
        push: true
        source: local

    - name: Save image tag to file for sharing
      copy:
        content: "{{ unique_tag }}"
        dest: /tmp/image_tag.txt